// ========================================================
// NOURII STORE - CATALOG DATA (قائمة المنتجات والأقسام)
// ========================================================

const CATEGORIES = [
  {
    id: "concrete",
    nameAr: "كونكريت للتلوين",
    nameEn: "Concrete for Coloring",
    icon: "fa-palette",
    image: "assets/images/concrete-coloring.jpg",
    descriptionAr: "مجسمات وأشكال كونكريت وجبس مجهزة للتلوين للأطفال والكبار مع ألوان وفرش لإطلاق العنان للإبداع.",
    descriptionEn: "Handcrafted concrete figurines and letters ready for painting with included colors and brushes."
  },
  {
    id: "coloring_books",
    nameAr: "كتب تلوين",
    nameEn: "Coloring Books",
    icon: "fa-book-open",
    image: "assets/images/coloring-books.jpg",
    descriptionAr: "كتب ودفاتر تلوين ورقية برسومات مانديلا وزخارف هندسية وحيوانات مع ألوان خشبية.",
    descriptionEn: "Mindful Mandala, geometric patterns, and African safari coloring books with color pencils."
  },
  {
    id: "magnets_brooches",
    nameAr: "صور مغناطيس و بروش",
    nameEn: "Magnets & Brooches",
    icon: "fa-certificate",
    image: "assets/images/magnets-brooches.jpg",
    descriptionAr: "مغناطيس ثلاجة عائلي مخصص وبروشات خشبية ومعدنية لطيفة لكافة المهن والشخصيات.",
    descriptionEn: "Custom family photo fridge magnets, wooden pins, and cute career badges."
  },
  {
    id: "event_favors",
    nameAr: "توزيعات مناسبات",
    nameEn: "Event Favors & Giveaways",
    icon: "fa-gift",
    image: "assets/images/event-favors.jpg",
    descriptionAr: "توزيعات فاخرة للسبوع، المواليد، الخطوبة، عقد القران، وحنة العروس مطبوعة بالأسماء.",
    descriptionEn: "Luxury personalized favors for newborn baby showers, engagements, weddings, and henna."
  },
  {
    id: "notebooks",
    nameAr: "نوت بوك",
    nameEn: "Notebooks & Planners",
    icon: "fa-book-bookmark",
    image: "assets/images/notebooks.jpg",
    descriptionAr: "دفاتر ومفكرات يومية بأغلفة مخملية منقوشة بالذهب، قوائم مهام، وأقلام راقية.",
    descriptionEn: "Custom velvet & faux-leather planners embossed in gold foil with to-do lists and luxury pens."
  },
  {
    id: "islamic_prints",
    nameAr: "مطبوعات دينية",
    nameEn: "Islamic Prints",
    icon: "fa-mosque",
    image: "assets/images/islamic-prints.jpg",
    descriptionAr: "مصاحف سورة البقرة مخملية فاخرة، كروت أذكار الصباح والمساء، وباقات صدقة جارية.",
    descriptionEn: "Royal velvet Quran covers, laminated Azkar morning/evening cards, and Sadaqah Jariyah favor packs."
  },
  {
    id: "educational_kids",
    nameAr: "ادوات تعليمية للاطفال",
    nameEn: "Educational Kids Tools",
    icon: "fa-shapes",
    image: "assets/images/educational-kids.jpg",
    descriptionAr: "بطاقات الحروف الهجائية، كتاب أبجد هوز، وسائل تفاعلية، وأرقام ومكعبات خشبية مبتكرة.",
    descriptionEn: "Arabic alphabet flashcards, interactive learning workbooks, wooden blocks, and educational kits."
  },
  {
    id: "luxury_prints",
    nameAr: "مطبوعات",
    nameEn: "Luxury Prints & Stationery",
    icon: "fa-envelope-open-text",
    image: "assets/images/luxury-prints.jpg",
    descriptionAr: "كروت إهداء مع أختام شمع راقية، فواصل كتب باقتباسات ملهمة، وأكياس هدايا فخمة.",
    descriptionEn: "Wax-sealed luxury envelopes, quote bookmarks, gift tags, and embossed celebration gift bags."
  },
  {
    id: "stickers",
    nameAr: "استيكرز",
    nameEn: "Stickers & Washi Tapes",
    icon: "fa-note-sticky",
    image: "assets/images/stickers.jpg",
    descriptionAr: "استيكرز فينيل ضد الماء (الفنان الصغير)، عبارات تحفيزية، وشرائط واشي تيب مبهجة.",
    descriptionEn: "Waterproof vinyl sticker packs, motivational artist decals, and colorful decorative washi tapes."
  },
  {
    id: "others",
    nameAr: "اخرى",
    nameEn: "Others & Home Accents",
    icon: "fa-gem",
    image: "assets/images/others.jpg",
    descriptionAr: "قواعد أكواب ريزن بالورد الطبيعي، ميداليات جلدية منقوشة، فواحات عطرية خزفية وبراويز ميني.",
    descriptionEn: "Real dried-flower resin coasters, genuine leather keychains, ceramic reed diffusers, and 3D frames."
  }
];

const PRODUCTS = [
  // 1. Concrete
  {
    id: "prod-conc-1",
    categoryId: "concrete",
    nameAr: "بوكس الفنان الصغير لتلوين الكونكريت",
    nameEn: "Little Artist Concrete Painting Kit",
    price: 195,
    originalPrice: 240,
    image: "assets/images/concrete-coloring.jpg",
    badgeAr: "الأكثر طلباً ⭐",
    badgeEn: "Best Seller",
    rating: 4.9,
    reviewsCount: 38,
    isCustomizable: true,
    customFieldLabelAr: "الاسم أو الشكل المفضل (بومة / فيل / مئذنة)",
    customFieldLabelEn: "Preferred Figurine (Owl / Elephant / Minaret)",
    descriptionAr: "مجموعة فنية متكاملة تحتوي على مجسمات كونكريت ناعمة الملمس وجاهزة للتلوين، 6 ألوان أكريليك زاهية آمنة للأطفال، فرش رسم، وباليت لتفريغ الألوان.",
    descriptionEn: "Complete artistic DIY kit featuring smooth handcrafted concrete figurines, 6 vibrant non-toxic paints, brushes, and a palette."
  },
  {
    id: "prod-conc-2",
    categoryId: "concrete",
    nameAr: "مجسم مئذنة ومسجد كونكريت للتلوين",
    nameEn: "Concrete Mosque & Minaret Painting Craft",
    price: 120,
    originalPrice: 150,
    image: "assets/images/concrete-coloring.jpg",
    badgeAr: "مميز للمناسبات 🌙",
    badgeEn: "Special Edition",
    rating: 5.0,
    reviewsCount: 24,
    isCustomizable: true,
    customFieldLabelAr: "الاسم المراد نقشه على القاعدة (اختياري)",
    customFieldLabelEn: "Name to engrave on base (optional)",
    descriptionAr: "مجسم هندسي أنيق لمسجد ومئذنة مصنوع من الكونكريت المصقول، نشاط روحاني وإبداعي رائع للأطفال في شهر رمضان والأعياد.",
    descriptionEn: "Handcrafted architectural concrete mosque and minaret figurine ready to paint with included warm tones."
  },
  {
    id: "prod-conc-3",
    categoryId: "concrete",
    nameAr: "طقم حروف كونكريت مخصصة باسمك مع ألوان",
    nameEn: "Personalized Concrete Name Letters with Paints",
    price: 160,
    originalPrice: 190,
    image: "assets/images/concrete-coloring.jpg",
    badgeAr: "تخصيص كامل ✏️",
    badgeEn: "Fully Custom",
    rating: 4.8,
    reviewsCount: 19,
    isCustomizable: true,
    customFieldLabelAr: "اكتب الحروف أو الاسم المطلوب بالإنجليزية أو العربية",
    customFieldLabelEn: "Type name letters (e.g., NOUR)",
    descriptionAr: "حروف كونكريت ثلاثية الأبعاد باسم طفلك أو من تحب، تأتي مع علبة ألوان وفرشاة لتلوينها والاحتفاظ بها كقطعة ديكور فريدة.",
    descriptionEn: "3D concrete alphabet letters customized with your chosen name, ready for custom painting and keepsake display."
  },

  // 2. Coloring Books
  {
    id: "prod-cb-1",
    categoryId: "coloring_books",
    nameAr: "كتاب تلوين المانديلا والزخارف الهندسية الفاخر",
    nameEn: "Mandala & Geometric Designs Premium Coloring Book",
    price: 95,
    originalPrice: 120,
    image: "assets/images/coloring-books.jpg",
    badgeAr: "للاسترخاء 🌸",
    badgeEn: "Relaxing Art",
    rating: 4.9,
    reviewsCount: 42,
    isCustomizable: false,
    descriptionAr: "كتاب تلوين فاخر يحتوي على أكثر من 40 تصميماً من زخارف المانديلا الدقيقة والأشكال الهندسية، مطبوع على ورق سميك عالي الجودة يمنع تسرب الألوان.",
    descriptionEn: "Premium coloring book with 40+ intricate mandala and geometric patterns on heavyweight bleed-proof paper."
  },
  {
    id: "prod-cb-2",
    categoryId: "coloring_books",
    nameAr: "كتيب تلوين حيوانات السفاري الأفريقية مع علبة ألوان",
    nameEn: "African Safari Creatures Coloring Booklet + Pencils",
    price: 85,
    originalPrice: 105,
    image: "assets/images/coloring-books.jpg",
    badgeAr: "محبوب الأطفال 🦁",
    badgeEn: "Kids Favorite",
    rating: 4.9,
    reviewsCount: 31,
    isCustomizable: false,
    descriptionAr: "كتيب رسومات كرتونية ظريفة لحيوانات الغابة الأفريقية مصمم لتقوية التركيز والتناسق البصري الحركي لدى الأطفال، يشمل علبة 12 قلم تلوين خشبي ناعم.",
    descriptionEn: "Charming safari animal coloring booklet for young artists, bundled with a 12-pack of colored pencils."
  },

  // 3. Magnets & Brooches
  {
    id: "prod-mb-1",
    categoryId: "magnets_brooches",
    nameAr: "مغناطيس ثلاجة عائلي مخصص بشكل قلب",
    nameEn: "Custom Family Heart Fridge Magnet",
    price: 65,
    originalPrice: 85,
    image: "assets/images/magnets-brooches.jpg",
    badgeAr: "هدية دافئة ❤️",
    badgeEn: "Warm Gift",
    rating: 5.0,
    reviewsCount: 56,
    isCustomizable: true,
    customFieldLabelAr: "أفراد العائلة أو الرسمة المطلوبة (أب، أم، أطفال)",
    customFieldLabelEn: "Family members to feature (Dad, Mom, Kids)",
    descriptionAr: "مغناطيس ثلاجة بقاعدة خشبية بشكل قلب مع رسم كرتوني يمثل عائلتك، مغلف بطبقة حماية لامعة مقاومة للماء والخدوش.",
    descriptionEn: "Heart-shaped wooden fridge magnet customized with your family cartoon illustration and waterproof gloss finish."
  },
  {
    id: "prod-mb-2",
    categoryId: "magnets_brooches",
    nameAr: "مجموعة بروشات ودبابيس المهن اللطيفة",
    nameEn: "Cute Career Badge Pins & Brooches Set",
    price: 80,
    originalPrice: 100,
    image: "assets/images/magnets-brooches.jpg",
    badgeAr: "أشكال متنوعة 👩‍⚕️",
    badgeEn: "Multi-Style",
    rating: 4.8,
    reviewsCount: 27,
    isCustomizable: true,
    customFieldLabelAr: "اختر المهنة (طبيب / مهندس / معلم / فنان / شيف)",
    customFieldLabelEn: "Select profession (Doctor / Engineer / Teacher / Artist)",
    descriptionAr: "دبابيس وبروشات معدنية وخشبية برسومات مميزة لشخصيات المهن، مثالية كهدية تخرج أو للتزيين على الحقائب والملابس.",
    descriptionEn: "Delightful profession pins (Doctor, Engineer, Chef, Artist) with secure metal clasp backing."
  },

  // 4. Event Favors
  {
    id: "prod-ef-1",
    categoryId: "event_favors",
    nameAr: "توزيعات المواليد والسبوع الملكية (باك 12 قطعة)",
    nameEn: "Royal Newborn Baby Shower Favors (Pack of 12)",
    price: 280,
    originalPrice: 340,
    image: "assets/images/event-favors.jpg",
    badgeAr: "مواليد جدد 🍼",
    badgeEn: "Baby Shower",
    rating: 5.0,
    reviewsCount: 64,
    isCustomizable: true,
    customFieldLabelAr: "اسم المولود وتاريخ المناسبة",
    customFieldLabelEn: "Baby Name & Date of Event",
    descriptionAr: "علب توزيعات أنيقة برسمة فيل لطيف أو دب كرتوني، تشمل حبات شوكولاتة فاخرة، كيس قماشي مع سبحة ميني، وكارت إهداء مطبوع باسم المولود.",
    descriptionEn: "Exquisite baby shower favor boxes with customized baby name tag, luxury chocolate, mini tasbeeh, and pouch."
  },
  {
    id: "prod-ef-2",
    categoryId: "event_favors",
    nameAr: "طقم توزيعات عقد القران والزفاف الفاخر",
    nameEn: "Luxury Katb Ktab & Wedding Favor Set",
    price: 450,
    originalPrice: 520,
    image: "assets/images/event-favors.jpg",
    badgeAr: "عقد قران مبارك 💍",
    badgeEn: "Wedding Edition",
    rating: 4.9,
    reviewsCount: 48,
    isCustomizable: true,
    customFieldLabelAr: "اسمي العروسين وتاريخ عقد القران",
    customFieldLabelEn: "Couples Names & Event Date",
    descriptionAr: "توزيعات عقد القران الفاخرة تتضمن مصحفاً ميني مخملياً، سبحة كريستالية بلون عنبري، وثيقة عقد قران مصغرة، ومروحة ورقية كلاسيكية.",
    descriptionEn: "Luxury Islamic wedding favors with mini velvet Quran, amber-tone tasbeeh, wedding scroll, and silk fan."
  },
  {
    id: "prod-ef-3",
    categoryId: "event_favors",
    nameAr: "مجموعة توزيعات حنة العروس التراثية",
    nameEn: "Bridal Henna Night Favors Collection",
    price: 390,
    originalPrice: 460,
    image: "assets/images/event-favors.jpg",
    badgeAr: "حنة العروس 🌺",
    badgeEn: "Henna Night",
    rating: 4.9,
    reviewsCount: 22,
    isCustomizable: true,
    customFieldLabelAr: "اسم العروس للطباعة على الظرف والمرآة",
    customFieldLabelEn: "Bride Name for Envelope and Mirror",
    descriptionAr: "باقة حنة راقية تشمل مرآة يدوية بزخارف شرقية ملونة، بوكس فانوس مخرم، حبات بخور أو مسك عطري، وظرف إهداء مطبوع بعبارة حنة العروس.",
    descriptionEn: "Authentic bridal henna favors featuring oriental hand mirror, die-cut lantern box, and perfumed musk."
  },

  // 5. Notebooks
  {
    id: "prod-nb-1",
    categoryId: "notebooks",
    nameAr: "نوت بوك ملكي جلد وردي منقوش بالذهب باسمك",
    nameEn: "Rose Gold Foil Personalized Leather Journal",
    price: 175,
    originalPrice: 220,
    image: "assets/images/notebooks.jpg",
    badgeAr: "تطريز ذهبي ✨",
    badgeEn: "Gold Foil Name",
    rating: 5.0,
    reviewsCount: 52,
    isCustomizable: true,
    customFieldLabelAr: "الاسم المراد نقشه بالذهب (مثال: نور / سارة)",
    customFieldLabelEn: "Name to engrave in gold (e.g., Noor)",
    descriptionAr: "نوت بوك جلدي فاخر بلون وردي ناعم، منقوش عليه اسمك بخط عربي ديواني باللون الذهبي البارز، مع أوراق عاجية مسطرة 100 جرام وشريط إشارة حريري.",
    descriptionEn: "Sophisticated dusty rose faux-leather journal with your name stamped in gold Arabic calligraphy on 100gsm cream paper."
  },
  {
    id: "prod-nb-2",
    categoryId: "notebooks",
    nameAr: "طقم التدوين المتكامل (نوت بوك + To Do List + قلم ذهبي)",
    nameEn: "Executive Stationery Gift Set (Journal + Notepad + Gold Pen)",
    price: 260,
    originalPrice: 310,
    image: "assets/images/notebooks.jpg",
    badgeAr: "طقم هدايا راقي 🎁",
    badgeEn: "Full Gift Set",
    rating: 4.9,
    reviewsCount: 39,
    isCustomizable: true,
    customFieldLabelAr: "الاسم المطلوب على النوت بوك والقلم",
    customFieldLabelEn: "Name for Journal and Pen engraving",
    descriptionAr: "طقم هدية متكامل يشمل دفتر يوميات، مفكرة مهام يومية (To Do List)، نوتباد صغير، قلم ذهبي منقوش بالاسم، ومشبك ذهبي أنيق مع شريط واشي تيب.",
    descriptionEn: "Complete desk gift set including journal, tear-off daily task pad, pocket notepad, custom engraved gold pen, and clips."
  },

  // 6. Islamic Prints
  {
    id: "prod-ip-1",
    categoryId: "islamic_prints",
    nameAr: "مصحف سورة البقرة مخمل ملكي أخضر مع قلم مذهب",
    nameEn: "Royal Green Velvet Surah Al-Baqarah Quran + Gold Pen",
    price: 220,
    originalPrice: 270,
    image: "assets/images/islamic-prints.jpg",
    badgeAr: "مخمل ملكي 🌿",
    badgeEn: "Royal Velvet",
    rating: 5.0,
    reviewsCount: 59,
    isCustomizable: true,
    customFieldLabelAr: "اسم الإهداء أو الصدقة الجارية (اختياري)",
    customFieldLabelEn: "Dedication or Name (optional)",
    descriptionAr: "مصحف سورة البقرة كاملة بغلاف مخملي أخضر زمردي بنقوش عربية ذهبية بارزة، مع قلم أنيق وحافظة مخملية وكرت أذكار الصباح والمساء.",
    descriptionEn: "Exquisite emerald-green velvet cover Surah Al-Baqarah edition with gilded ornaments, gold pen, and Azkar card."
  },
  {
    id: "prod-ip-2",
    categoryId: "islamic_prints",
    nameAr: "كروت أذكار الصباح والمساء وأذكار بعد الصلاة (مصفحة)",
    nameEn: "Laminated Morning & Evening Azkar Card Set",
    price: 75,
    originalPrice: 95,
    image: "assets/images/islamic-prints.jpg",
    badgeAr: "حجم مناسب للجيب 📿",
    badgeEn: "Pocket Size",
    rating: 4.9,
    reviewsCount: 44,
    isCustomizable: false,
    descriptionAr: "كروت أنيقة مطبوعة بخط واضح ومصفحة بطبقة حماية ضد التلف والماء، تضم أذكار الصباح والمساء كاملة وأذكار ما بعد الصلوات المكتوبة.",
    descriptionEn: "Crystal-clear laminated Azkar cards for daily remembrance, pocket-sized and protected against water and wear."
  },
  {
    id: "prod-ip-3",
    categoryId: "islamic_prints",
    nameAr: "باقات صدقة جارية مخصصة (باك 20 كارت وميني مصحف)",
    nameEn: "Custom Sadaqah Jariyah Remembrance Pack (20 Units)",
    price: 350,
    originalPrice: 420,
    image: "assets/images/islamic-prints.jpg",
    badgeAr: "صدقة جارية 🤲",
    badgeEn: "Sadaqah Jariyah",
    rating: 5.0,
    reviewsCount: 36,
    isCustomizable: true,
    customFieldLabelAr: "اسم المتوفى أو صاحب الصدقة للدعاء",
    customFieldLabelEn: "Name for Dedication and Prayers",
    descriptionAr: "باقات توزيعات راقية مع ربطة فيونكة ستان خضراء وذهبية، تشمل مصاحف ميني وكروت دعاء مطبوعة باسم من تحبون كصدقة جارية.",
    descriptionEn: "Elegantly wrapped memorial gift favors with ribbon bows, mini Qurans, and personalized dua cards."
  },

  // 7. Educational Kids Tools
  {
    id: "prod-ek-1",
    categoryId: "educational_kids",
    nameAr: "كتاب تفاعلي أبجد هوز لتعليم القراءة والكتابة",
    nameEn: "Interactive Abjad Hawaz Arabic Alphabet Activity Book",
    price: 145,
    originalPrice: 180,
    image: "assets/images/educational-kids.jpg",
    badgeAr: "تفاعلي وممتع 🧩",
    badgeEn: "Interactive Fun",
    rating: 4.9,
    reviewsCount: 47,
    isCustomizable: true,
    customFieldLabelAr: "اسم الطفل للطباعة على غلاف الكتاب",
    customFieldLabelEn: "Child's name for cover customization",
    descriptionAr: "كتاب ألعاب تعليمية ملون يدمج بين المرح والتعلم، يحتوي على أنشطة تتبع الحروف، تلوين الكلمات، وتوصيل الحروف بالأشياء اليومية.",
    descriptionEn: "Engaging hardcover educational book teaching Arabic alphabet and phonetics through playful exercises."
  },
  {
    id: "prod-ek-2",
    categoryId: "educational_kids",
    nameAr: "فلاش كاردز الحروف والحيوانات التفاعلية للأطفال",
    nameEn: "Arabic Alphabet & Animals Flashcards Set",
    price: 95,
    originalPrice: 120,
    image: "assets/images/educational-kids.jpg",
    badgeAr: "كرتون متين 🍎",
    badgeEn: "Durable Cards",
    rating: 4.8,
    reviewsCount: 29,
    isCustomizable: false,
    descriptionAr: "28 بطاقة تعليمية سميكة بحواف دائرية آمنة، مطبوعة برسومات ملونة وأسماء واضحة (أ - تفاحة، د - دب، س - سيارة) لتوسيع المفردات اللغوية للطفل.",
    descriptionEn: "28 thick rounded-edge flashcards showcasing Arabic letters and illustrated vocabulary words."
  },
  {
    id: "prod-ek-3",
    categoryId: "educational_kids",
    nameAr: "حقيبة التوزيعات التعليمية الذكية (مكعبات + عدسة + بوصلة)",
    nameEn: "Little Explorer Educational Favor Kit (Blocks + Lens)",
    price: 185,
    originalPrice: 225,
    image: "assets/images/educational-kids.jpg",
    badgeAr: "المستكشف الصغير 🔍",
    badgeEn: "Young Explorer",
    rating: 4.9,
    reviewsCount: 21,
    isCustomizable: true,
    customFieldLabelAr: "اسم المناسبة أو أسماء الأطفال",
    customFieldLabelEn: "Event or Children's Names",
    descriptionAr: "حقيبة هدايا تعليمية في أظرف قماشية ملونة، تحتوي على عدسة مكبرة للاستكشاف، بوصلة صغيرة، ومكعبات بناء ملونة مع قلم ممتع.",
    descriptionEn: "Fabric pouch favor kit packed with a magnifying glass, beginner compass, building blocks, and an activity pen."
  },

  // 8. Luxury Prints
  {
    id: "prod-lp-1",
    categoryId: "luxury_prints",
    nameAr: "أظرف كلاسيكية فاخرة بختم شمع حقيقي وكروت تهنئة",
    nameEn: "Real Wax-Sealed Classic Gift Envelopes & Cards",
    price: 110,
    originalPrice: 135,
    image: "assets/images/luxury-prints.jpg",
    badgeAr: "ختم شمع ملكي ✉️",
    badgeEn: "Wax Sealed",
    rating: 5.0,
    reviewsCount: 38,
    isCustomizable: true,
    customFieldLabelAr: "العبارة المطبوعة (تهانينا / مبروك / لك)",
    customFieldLabelEn: "Printed Text (Congratulations / For You / Mabrouk)",
    descriptionAr: "أظرف راقية بلون أخضر ملكي وعاجي مغلقة بأختام شمع ذهبية مع كروت تهنئة سميكة بحروف محفورة بالذهب لمناسباتكم الخاصة.",
    descriptionEn: "Luxury textured stationery envelopes with authentic gold wax seals and gold foil letterpress cards."
  },
  {
    id: "prod-lp-2",
    categoryId: "luxury_prints",
    nameAr: "طقم فواصل كتب فاخرة باقتباسات ملهمة (3 قطع)",
    nameEn: "Inspiring Quotes Luxury Bookmark Set (Pack of 3)",
    price: 60,
    originalPrice: 75,
    image: "assets/images/luxury-prints.jpg",
    badgeAr: "لعشاق القراءة 📖",
    badgeEn: "Book Lovers",
    rating: 4.8,
    reviewsCount: 26,
    isCustomizable: false,
    descriptionAr: "ثلاثة فواصل كتب مطبوعة على ورق قطني سميك برسومات فنية وتطريز أشرطة قماشية فاخرة، مع عبارات اقتباس اليوم وشكراً.",
    descriptionEn: "Set of 3 artistic cotton-paper bookmarks featuring warm botanical illustrations, quote typography, and ribbon ties."
  },
  {
    id: "prod-lp-3",
    categoryId: "luxury_prints",
    nameAr: "أكياس هدايا راقية بنقش ذهبي بارز لمناسباتكم الخاصة",
    nameEn: "Embossed Luxury Gift Bags with Fabric Handles",
    price: 85,
    originalPrice: 110,
    image: "assets/images/luxury-prints.jpg",
    badgeAr: "تقديم فاخر 🛍️",
    badgeEn: "Luxury Bag",
    rating: 4.9,
    reviewsCount: 19,
    isCustomizable: true,
    customFieldLabelAr: "اختر العبارة (مناسبة خاصة / أطيب التمنيات)",
    customFieldLabelEn: "Choose Text (Special Occasion / Best Wishes)",
    descriptionAr: "حقائب هدايا كرتونية فاخرة متوفرة بالأزرق الكحلي والأبيض العاجي، بنقوش إسلامية بارزة وطباعة ذهبية وحزام يد قماشي متين.",
    descriptionEn: "High-density embossed paper gift bags with opulent arabesque patterns and sturdy woven handles."
  },

  // 9. Stickers
  {
    id: "prod-st-1",
    categoryId: "stickers",
    nameAr: "باك استيكرز الفنان الصغير ضد الماء والتمزق",
    nameEn: "Little Artist Waterproof Vinyl Sticker Pack",
    price: 55,
    originalPrice: 70,
    image: "assets/images/stickers.jpg",
    badgeAr: "مقاوم للماء 🎨",
    badgeEn: "Waterproof Vinyl",
    rating: 4.9,
    reviewsCount: 45,
    isCustomizable: false,
    descriptionAr: "مجموعة ملصقات فينيل عالية الجودة بتصاميم كرتونية مرحة لأدوات الرسم والفرش والألوان وشخصيات الفنان الصغير، مثالية لتزيين الدفاتر واللابتوب.",
    descriptionEn: "Vibrant vinyl die-cut stickers depicting art supplies, mini easels, and cute artist characters; fully waterproof."
  },
  {
    id: "prod-st-2",
    categoryId: "stickers",
    nameAr: "شيت استيكرز عبارات تحفيزية ونجوم ذهبية",
    nameEn: "Motivational Stars & Quotes Sticker Sheet",
    price: 45,
    originalPrice: 60,
    image: "assets/images/stickers.jpg",
    badgeAr: "تشجيع للأطفال ⭐",
    badgeEn: "Motivational",
    rating: 4.8,
    reviewsCount: 33,
    isCustomizable: false,
    descriptionAr: "شيت ملصقات مميز بعبارات تحفيزية مشجعة مثل (الفن حياة، أنا فنان، أرسم مستقبلي) مع نجوم ذهبية لامعة لتكريم ومكافأة الأطفال.",
    descriptionEn: "Inspiring reward stickers with gold metallic stars and positive affirmation quotes in Arabic calligraphy."
  },
  {
    id: "prod-st-3",
    categoryId: "stickers",
    nameAr: "طقم شرائط واشي تيب مبهجة للتزيين (3 رولات)",
    nameEn: "Artistic Decorative Washi Tape Rolls (Set of 3)",
    price: 75,
    originalPrice: 95,
    image: "assets/images/stickers.jpg",
    badgeAr: "تزيين الدفاتر ✂️",
    badgeEn: "Washi Tape Set",
    rating: 4.9,
    reviewsCount: 22,
    isCustomizable: false,
    descriptionAr: "ثلاثة رولات واشي تيب ورقية يابانية سهلة اللصق والنزع بنقوش أدوات رسم وألوان مائية، لتزيين اليوميات والبطاقات والعلب.",
    descriptionEn: "Trio of premium Japanese washi tape rolls featuring colorful palette and paintbrush motifs; peel-and-stick."
  },

  // 10. Others
  {
    id: "prod-ot-1",
    categoryId: "others",
    nameAr: "قواعد أكواب ريزن بالورد الطبيعي المجفف والذهب",
    nameEn: "Real Pressed Flower & Gold Leaf Resin Coaster Set",
    price: 160,
    originalPrice: 200,
    image: "assets/images/others.jpg",
    badgeAr: "صناعة يدوية فريدة 🌸",
    badgeEn: "Handmade Resin",
    rating: 5.0,
    reviewsCount: 37,
    isCustomizable: true,
    customFieldLabelAr: "ألوان الزهور المفضلة (وردي / أبيض / لافندر)",
    customFieldLabelEn: "Flower color preference (Pink / White / Lavender)",
    descriptionAr: "قواعد أكواب فاخرة مصنوعة يدوياً من الريزن الشفاف عالي النقاوة، مدمجة بزهور طبيعية مجففة بعناية ورقائق ذهب عيار 24.",
    descriptionEn: "Hand-poured crystal clear resin coasters with real preserved botanical flowers and subtle gold flakes."
  },
  {
    id: "prod-ot-2",
    categoryId: "others",
    nameAr: "ميداليات مفاتيح جلدية طبيعية مع دلاية معدنية",
    nameEn: "Handcrafted Leather Keychain with Bronze Charm",
    price: 90,
    originalPrice: 115,
    image: "assets/images/others.jpg",
    badgeAr: "جلد طبيعي 🔑",
    badgeEn: "Genuine Leather",
    rating: 4.8,
    reviewsCount: 28,
    isCustomizable: true,
    customFieldLabelAr: "الحرف أو الاسم المراد نقشه على الجلد",
    customFieldLabelEn: "Initial or Name to stamp on leather",
    descriptionAr: "ميدالية مفاتيح مصنوعة من الجلد الطبيعي الفاخر مع حلقة نحاسية عتيقة ودلاية شجرة الحياة البرونزية، متوفرة بألوان كلاسيكية أنيقة.",
    descriptionEn: "Artisan genuine leather strap keychain with antique brass hardware and tree-of-life medallion."
  },
  {
    id: "prod-ot-3",
    categoryId: "others",
    nameAr: "فواحة عطرية خزفية شرقية مع أعواد خشبية وزيت عطري",
    nameEn: "Moroccan Ceramic Reed Diffuser + Fragrance Oil",
    price: 180,
    originalPrice: 220,
    image: "assets/images/others.jpg",
    badgeAr: "رائحة زكية 🌿",
    badgeEn: "Aromatherapy",
    rating: 4.9,
    reviewsCount: 31,
    isCustomizable: true,
    customFieldLabelAr: "اختر الرائحة (لافندر / مسك أبيض / فانيليا)",
    customFieldLabelEn: "Choose Scent (Lavender / White Musk / Vanilla)",
    descriptionAr: "فواحة سيراميك مزخرفة بنقوش أندلسية زرقاء دافئة، تأتي مع أعواد قصب خشبية وزجاجة زيت عطري مركز تدوم رائحته لأسابيع.",
    descriptionEn: "Artisanal glazed ceramic reed diffuser with Moroccan motifs, accompanied by natural rattan reeds and pure aroma oil."
  }
];

// REVIEWS & TESTIMONIALS
const REVIEWS = [
  {
    nameAr: "مريم عبد الله",
    nameEn: "Mariam Abdullah",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80",
    rating: 5,
    cityAr: "القاهرة",
    cityEn: "Cairo",
    commentAr: "طلبت بوكسات توزيعات السبوع ونوت بوك باسم نور.. الشغل نظيف جداً وتفاصيل الطباعة والذهب تفوق الوصف! كل الضيوف انبهروا بالتوزيعات. شكراً نوري!",
    commentEn: "Ordered baby shower favors and a custom gold-embossed notebook. The craftsmanship and attention to detail blew everyone away! Thank you Nourii!"
  },
  {
    nameAr: "سارة محمود",
    nameEn: "Sara Mahmoud",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
    rating: 5,
    cityAr: "الإسكندرية",
    cityEn: "Alexandria",
    commentAr: "مجموعة الكونكريت للتلوين غيرت مود أولادي تماماً، الألوان جودتها ممتازة والمجسمات ناعمة ومش بتتكسر بسهولة. تجربة شراء سهلة جداً عبر الواتساب.",
    commentEn: "The concrete painting kit was the highlight of our weekend! Non-toxic paints and very smooth figurines. Seamless WhatsApp ordering."
  },
  {
    nameAr: "أحمد الفقي",
    nameEn: "Ahmed El-Feqy",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    rating: 5,
    cityAr: "الجيزة",
    cityEn: "Giza",
    commentAr: "مصحف سورة البقرة المخمل الأخضر فخم جداً ينفع هدية تليق بأي مناسبة. التغليف والختم الشمعي شيء راقي جداً.",
    commentEn: "The emerald velvet Quran is pure elegance. The packaging with real wax seals felt like a royal gift."
  }
];

// FAQS
const FAQS = [
  {
    qAr: "كيف يتم تأكيد الطلب والبدء في تنفيذه؟",
    qEn: "How is the order confirmed and processed?",
    aAr: "بمجرد إتمام اختيار المنتجات والضغط على زر 'إرسال الطلب عبر واتساب'، تفتح محادثة واتساب مباشرة بتفاصيل طلبك، ويقوم فريق Nourii بالرد فوراً لتأكيد التفاصيل والبدء بالتنفيذ.",
    aEn: "Once you finalize items and click 'Order via WhatsApp', a pre-formatted message opens directly with Nourii's team to confirm personalization and start crafting."
  },
  {
    qAr: "كم تستغرق مدة تجهيز المنتجات اليدوية والمخصصة؟",
    qEn: "How long does custom crafting take?",
    aAr: "المنتجات الجاهزة تشحن خلال 24 إلى 48 ساعة. أما التوزيعات والطلبات المخصصة بأسماء أو صب كونكريت خاص فتستغرق من 3 إلى 5 أيام عمل لضمان أعلى درجات الجودة.",
    aEn: "Ready-stock items ship within 24-48 hours. Custom name engravings and handmade concrete take 3-5 business days."
  },
  {
    qAr: "هل متاح الشحن والتوصيل لجميع المحافظات؟",
    qEn: "Do you deliver to all governorates?",
    aAr: "نعم، نقوم بالشحن والتوصيل لكافة محافظات جمهورية مصر العربية عبر شركات شحن سريعة ومضمونة حتى باب المنزل.",
    aEn: "Yes, we deliver across all governorates via secure fast door-to-door courier services."
  },
  {
    qAr: "هل يمكن طلب كميات كبيرة للمناسبات وحفلات التخرج مع خصم؟",
    qEn: "Can I order bulk quantities with discounts for events?",
    aAr: "بالتأكيد! نوفر أسعاراً مخفضة للكميات بدءاً من 25 قطعة للمدارس والشركات والمناسبات الخاصة، ويمكنك استخدام 'صانع التوزيعات الذكي' في الموقع لحساب الخصم فورا.",
    aEn: "Absolutely! We provide tiered bulk discounts starting at 25 units. You can use our Smart Giveaways Estimator right on the site!"
  }
];
